stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - "cd Mosaik.id"
    - "docker build -t mosaik.idapi ."

test-job1:
  stage: test
  script:
    - "cd Mosaik.id/Mosaik.idTest"
    - "dotnet test"


deploy-prod:
  stage: deploy
  script:
    - "cd Mosaik.id"
    -  "heroku container:push -a mosaik-id-ppl web "
    -  "heroku container:release -a mosaik-id-ppl web" 
